// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Test } from "forge-std/Test.sol";
import { PerihelionEscrow } from "../src/PerihelionEscrow.sol";

/// @dev Cross-language validation: decode Rust-generated payloads and assert
/// the Solidity decoder produces identical results or rejects identically.
///
/// This test reads payloads exported by the Rust proptest fuzzer from
/// `contracts/shared/wire-vectors/fuzz-corpus/*.hex` and validates them
/// against the Solidity decoder.
///
/// Run after generating the Rust corpus:
///   cd contracts/soroban/settlement
///   PROPTEST_CASES=100 cargo test fuzz
///   cd ../../evm
///   forge test --match-contract CrossValidate
contract CrossValidateTest is Test {
    DecoderHarness internal harness;

    string internal constant CORPUS_DIR = "../shared/wire-vectors/fuzz-corpus/";

    function setUp() public {
        harness = new DecoderHarness(address(0x1), 30_316);
    }

    /// @dev Cross-validate Rust-generated FillConfirmed payloads with nonzero high bytes.
    /// The Rust encoder allows this (it's a pass-through), but the Solidity decoder
    /// MUST reject it to prevent address redirection.
    function testCrossValidateCorpus_FillConfirmedNonzeroHigh() public {
        string memory path = string.concat(CORPUS_DIR, "fill_confirmed_nonzero_high.hex");
        
        // Skip if file doesn't exist (corpus not generated yet)
        try vm.readFile(path) returns (string memory hexData) {
            bytes memory payload = vm.parseBytes(hexData);
            
            // This payload was generated by Rust and is structurally valid on that side,
            // but must be rejected by Solidity due to nonzero high bytes in solver_evm.
            vm.expectRevert(PerihelionEscrow.MalformedPayload.selector);
            harness.decodeFillConfirmed(payload);
        } catch {
            // File doesn't exist, skip test
            vm.skip(true);
        }
    }

    /// @dev Cross-validate Rust-generated CancelIntent payloads with bad reason codes.
    function testCrossValidateCorpus_CancelIntentBadReason() public {
        string memory path = string.concat(CORPUS_DIR, "cancel_intent_bad_reason.hex");
        
        try vm.readFile(path) returns (string memory hexData) {
            bytes memory payload = vm.parseBytes(hexData);
            
            vm.expectRevert(PerihelionEscrow.MalformedPayload.selector);
            harness.decodeCancelIntent(payload);
        } catch {
            vm.skip(true);
        }
    }

    /// @dev General corpus validation: read all .hex files in fuzz-corpus/
    /// and attempt to decode. Log any unexpected results.
    function testCrossValidateCorpus() public {
        // List all .hex files in the corpus directory
        string[] memory files = _listCorpusFiles();
        
        if (files.length == 0) {
            // No corpus files, skip
            vm.skip(true);
            return;
        }

        uint256 validated = 0;
        uint256 rejected = 0;
        uint256 errors = 0;

        for (uint256 i = 0; i < files.length; i++) {
            string memory path = string.concat(CORPUS_DIR, files[i]);
            bytes memory payload = vm.parseBytes(vm.readFile(path));

            // Determine expected behavior from filename
            bool shouldReject = _shouldReject(files[i]);

            if (shouldReject) {
                // Expect rejection
                try harness.routeInbound(payload) {
                    emit log_string(string.concat("UNEXPECTED ACCEPT: ", files[i]));
                    errors++;
                } catch {
                    rejected++;
                }
            } else {
                // Expect success
                try harness.routeInbound(payload) {
                    validated++;
                } catch {
                    emit log_string(string.concat("UNEXPECTED REJECT: ", files[i]));
                    errors++;
                }
            }
        }

        emit log_named_uint("Validated payloads", validated);
        emit log_named_uint("Rejected payloads", rejected);
        emit log_named_uint("Unexpected results", errors);

        assertEq(errors, 0, "Cross-validation detected codec divergence");
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    function _listCorpusFiles() internal view returns (string[] memory) {
        // In a real implementation, we'd read the directory.
        // For now, return a fixed list of expected files.
        string[] memory files = new string[](2);
        files[0] = "fill_confirmed_nonzero_high.hex";
        files[1] = "cancel_intent_bad_reason.hex";
        return files;
    }

    function _shouldReject(string memory filename) internal pure returns (bool) {
        // Files with "bad", "nonzero", "unknown", "short", "long" should be rejected
        bytes memory name = bytes(filename);
        return _contains(name, "bad") ||
               _contains(name, "nonzero") ||
               _contains(name, "unknown") ||
               _contains(name, "short") ||
               _contains(name, "long");
    }

    function _contains(bytes memory haystack, bytes memory needle) internal pure returns (bool) {
        if (needle.length > haystack.length) return false;
        
        for (uint256 i = 0; i <= haystack.length - needle.length; i++) {
            bool found = true;
            for (uint256 j = 0; j < needle.length; j++) {
                if (haystack[i + j] != needle[j]) {
                    found = false;
                    break;
                }
            }
            if (found) return true;
        }
        return false;
    }
}

/// @dev Reuse the harness from DifferentialFuzz.t.sol
contract DecoderHarness is PerihelionEscrow {
    constructor(address endpoint_, uint32 eid_) PerihelionEscrow(endpoint_, eid_) { }

    function decodeFillConfirmed(bytes calldata m) external pure returns (bytes32, address, uint128, uint64) {
        return _decodeFillConfirmed(m);
    }

    function decodeCancelIntent(bytes calldata m) external pure returns (bytes32, uint8) {
        return _decodeCancelIntent(m);
    }

    function routeInbound(bytes calldata m) external {
        if (m.length < 2 || m[0] != 0x01) revert MalformedPayload();
        bytes1 msgType = m[1];
        if (msgType == 0x02) {
            _decodeFillConfirmed(m);
        } else if (msgType == 0x03) {
            _decodeCancelIntent(m);
        } else {
            revert UnknownMessageType();
        }
    }
}
